services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    env_file: .env
    volumes:
      - ./outputs:/outputs
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    environment:
      - API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api
